import { DarkTheme, DefaultTheme, type Theme } from '@react-navigation/native';
 
export const THEME = {
  light: {
    background: '#eff1f5',
    foreground: '#4c4f69',
    card: '#ffffff',
    cardForeground: '#4c4f69',
    popover: '#ccd0da',
    popoverForeground: '#4c4f69',
    primary: '#8839ef',
    primaryForeground: '#ffffff',
    secondary: '#ccd0da',
    secondaryForeground: '#4c4f69',
    muted: '#dce0e8',
    mutedForeground: '#6c6f85',
    accent: '#04a5e5',
    accentForeground: '#ffffff',
    destructive: '#d20f39',
    destructiveForeground: '#ffffff',
    border: '#bcc0cc',
    input: '#ccd0da',
    ring: '#8839ef',
    radius: '0.35rem',
    chart1: '#8839ef',
    chart2: '#04a5e5',
    chart3: '#40a02b',
    chart4: '#fe640b',
    chart5: '#dc8a78',
  },
  dark: {
    background: '#181825',
    foreground: '#cdd6f4',
    card: '#1e1e2e',
    cardForeground: '#cdd6f4',
    popover: '#45475a',
    popoverForeground: '#cdd6f4',
    primary: '#cba6f7',
    primaryForeground: '#1e1e2e',
    secondary: '#585b70',
    secondaryForeground: '#cdd6f4',
    muted: '#292c3c',
    mutedForeground: '#a6adc8',
    accent: '#89dceb',
    accentForeground: '#1e1e2e',
    destructive: '#f38ba8',
    destructiveForeground: '#1e1e2e',
    border: '#313244',
    input: '#313244',
    ring: '#cba6f7',
    radius: '0.35rem',
    chart1: '#cba6f7',
    chart2: '#89dceb',
    chart3: '#a6e3a1',
    chart4: '#fab387',
    chart5: '#f5e0dc',
  },
};
 
export const NAV_THEME: Record<'light' | 'dark', Theme> = {
  light: {
    ...DarkTheme,
    colors: {
      background: THEME.light.background,
      border: THEME.light.border,
      card: THEME.light.card,
      notification: THEME.light.destructive,
      primary: THEME.light.primary,
      text: THEME.light.foreground,
    },
  },
  dark: {
    ...DarkTheme,
    colors: {
      background: THEME.dark.background,
      border: THEME.dark.border,
      card: THEME.dark.card,
      notification: THEME.dark.destructive,
      primary: THEME.dark.primary,
      text: THEME.dark.foreground,
    },
  },
};
